openapi: 3.0.0
info:
  title: Wiki API
  version: 1.0.0
  description: Documentación de mi API con Swagger
servers:
  - url: http://localhost:3000
paths:
  # --- Managements ---
  /api/managements:
    post:
      tags: [Gestiones]
      summary: Crear una nueva gestión
      consumes:
        - multipart/form-data
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Título de la gestión
                description:
                  type: string
                  description: Descripción de la gestión
                keywords:
                  type: array
                  items:
                    type: string
                  description: Palabras clave (array de strings)
                rrhhId:
                  type: integer
                  description: ID del usuario creador
                categoryId:
                  type: integer
                  description: ID de la categoría
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos a subir
      responses:
        '201':
          description: Gestión creada exitosamente
    get:
      tags: [Gestiones]
      summary: Obtener todas las gestiones
      responses:
        '200':
          description: Lista de gestiones
  /api/managements/{id}:
    put:
      tags: [Gestiones]
      summary: Actualizar una gestión existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la gestión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                categoryId:
                  type: integer
      responses:
        '200':
          description: Gestión actualizada exitosamente
    get:
      tags: [Gestiones]
      summary: Obtener una gestión por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la gestión
      responses:
        '200':
          description: Gestión encontrada
    delete:
      tags: [Gestiones]
      summary: Eliminar (soft delete) una gestión
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la gestión
      responses:
        '200':
          description: Gestión eliminada exitosamente
  /api/managements/addFile/{id}:
    put:
      tags: [Gestiones]
      summary: Agregar archivos a una gestión existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la gestión
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos a agregar
      responses:
        '200':
          description: Archivos agregados exitosamente
  /api/managements/deleteFile/{id}:
    put:
      tags: [Gestiones]
      summary: Eliminar archivos de una gestión existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la gestión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                  description: Nombres de archivos a eliminar
      responses:
        '200':
          description: Archivos eliminados exitosamente
  /api/managements/updateFiles/{id}:
    put:
      tags: [Gestiones]
      summary: Agregar y/o eliminar archivos de una gestión existente (updateFiles)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la gestión
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos a agregar (opcional)
                filesToDelete:
                  type: array
                  items:
                    type: string
                  description: Nombres de archivos a eliminar (opcional)
      responses:
        '200':
          description: Archivos actualizados exitosamente
  /api/managements/pagination:
    post:
      tags: [Gestiones]
      summary: Obtener gestiones con paginación y filtros de búsqueda
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Número de página
        - in: query
          name: perPage
          schema:
            type: integer
          description: Cantidad de resultados por página
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryId:
                  type: integer
                  description: ID de la categoría (opcional)
                title:
                  type: string
                  description: Título de la gestión (opcional, búsqueda parcial)
                description:
                  type: string
                  description: Descripción de la gestión (opcional, búsqueda parcial)
                keywords:
                  type: array
                  items:
                    type: string
                  description: Palabras clave (opcional, array de strings)
      responses:
        200:
          description: Gestiones paginadas y filtradas
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Management'
                  first_page_url:
                    type: string
                  from:
                    type: integer
                  last_page:
                    type: integer
                  last_page_url:
                    type: string
                  next_page_url:
                    type: string
                    nullable: true
                  path:
                    type: string
                  per_page:
                    type: integer
                  prev_page_url:
                    type: string
                    nullable: true
                  to:
                    type: integer
                  total:
                    type: integer

  # --- Categories ---
  /api/categories:
    post:
      tags: [Categorías]
      summary: Crear una nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre de la categoría
                groupId:
                  type: integer
                  description: ID del grupo de la categoría
                rrhhId:
                  type: integer
                  description: ID del usuario creador
      responses:
        '201':
          description: Categoría creada exitosamente
    get:
      tags: [Categorías]
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
  /api/categories/{id}:
    get:
      tags: [Categorías]
      summary: Obtener una categoría por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la categoría
      responses:
        '200':
          description: Categoría encontrada
    put:
      tags: [Categorías]
      summary: Actualizar una categoría por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nuevo nombre de la categoría
                groupId:
                  type: integer
                  description: Nuevo ID de grupo de la categoría
      responses:
        '200':
          description: Categoría actualizada exitosamente
    delete:
      tags: [Categorías]
      summary: Eliminar una categoría por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID de la categoría
      responses:
        '200':
          description: Categoría eliminada exitosamente
  /api/categories/filterSegmentation:
    post:
      tags: [Categorías]
      summary: Obtener categorías por segmentación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupId:
                  type: integer
                  description: ID del grupo de la categoría
      responses:
        '200':
          description: Categorías filtradas por segmentación
  /api/categories/filterName:
    post:
      tags: [Categorías]
      summary: Obtener categorías por nombre
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre a buscar (parcial o completo)
                rrhhId:
                  type: integer
                  description: ID del usuario creador
      responses:
        '200':
          description: Categorías filtradas por nombre
  /api/categories/pagination:
    post:
      tags: [Categorías]
      summary: Obtener categorías con paginación y filtros opcionales
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Número de página
        - in: query
          name: perPage
          schema:
            type: integer
          description: Cantidad de resultados por página
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Filtrar por nombre (opcional, búsqueda parcial)
                groupId:
                  type: integer
                  description: Filtrar por ID de grupo (opcional)
      responses:
        200:
          description: Categorías paginadas
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                  first_page_url:
                    type: string
                  from:
                    type: integer
                  last_page:
                    type: integer
                  last_page_url:
                    type: string
                  next_page_url:
                    type: string
                    nullable: true
                  path:
                    type: string
                  per_page:
                    type: integer
                  prev_page_url:
                    type: string
                    nullable: true
                  to:
                    type: integer
                  total:
                    type: integer

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        groupId:
          type: integer
        rrhhId:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
          nullable: true
    Management:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        keywords:
          type: array
          items:
            type: string
          description: Palabras clave (array de strings)
        file:
          type: array
          items:
            type: string
          description: Palabras clave (array de strings)
        rrhhId:
          type: integer
        category:
          $ref: '#/components/schemas/Category'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
          nullable: true
