version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: wikidb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_wiki_dev
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: wikipassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: wikinode
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads

volumes:
  db_data:
